#MySQL container 

dbsql:
    restart: always
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: changeme
        MYSQL_USER: flis
        MYSQL_PASSWORD: flis
        MYSQL_DATABASE: flis

#Postgres container

dbpost:
    restart: always
    image: postgres:9.1
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: flis
        POSTGRES_PASSWORD: flis

#Horizon scanning tool

hstool:
    build: ./flis.horizon-scanning-tool
    restart: always
    links:
        - dbsql
    env_file:
        - ./hstool.env

#Flip

flip:
   build: ./flis.flip
   command:
       ./manage.py runserver 0.0.0.0:8001
   volumes:
       - ./flis.flip/flip/static
   links:
       - dbpost
   env_file:
       - ./dev.env

#Live catalogue

livecat:
    build: ./flis.live_catalogue
    command:
        ./manage.py runserver 0.0.0.0:8002
    volumes:
        - ./flis.live_catalogue/live_catalogue/static
    links:
        - dbsql
    env_file:
        - ./dev.env

#Frontend server

frontend:
    build: frontend
    restart: always
    links:
        - hstool
        - flip
        - livecat
    volumes_from:
        - hstool
        - flip
        - livecat
    ports:
        - 80:80
