#MySQL container 

dbsql:
    restart: always
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: changeme
        MYSQL_USER: flis
        MYSQL_PASSWORD: flis
        MYSQL_DATABASE: flis

#Postgres container

dbpost:
    restart: always
    image: postgres:9.1
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: flis
        POSTGRES_PASSWORD: flis

#Horizon scanning tool

hstool:
    build: ./flis.horizon-scanning-tool
    restart: always
    links:
        - dbsql
    env_file:
        - ./hstool.env

#Flip

flip:
   build: ./flis.flip
   restart: always
   links:
       - dbpost
   env_file:
       - ./flip.env

#Live catalogue

livecat:
    build: ./flis.live_catalogue
    restart: always
    links:
        - dbsql
    env_file:
        - ./livecat.env

#Metadata

metadata:
    build: ./flis.metadata
    restart: always
    links:
        - dbsql
    env_file:
        - ./metadata.env

#Frontend server

frontend:
    build: frontend
    restart: always
    links:
        - hstool
        - flip
        - livecat
	- metadata
    volumes_from:
        - hstool
        - flip
        - livecat
	- metadata
    ports:
        - 80:80
