#MySQL container 

dbsql:
    restart: always
    image: mysql:5.6
    ports:
        - "3306:3306"
    env_file:
        - env/dbsql.env

#Postgres container

dbpost:
    restart: always
    image: postgres:9.1
    ports:
        - "5432:5432"
    env_file:
        - env/dbpost.env

#Horizon scanning tool

hstool:
    restart: always
    image: eeacms/flis.hstool
    links:
        - dbsql
    env_file:
        - env/hstool.env

#Flip

flip:
   restart: always
   image: eeacms/flis.flip
   links:
       - dbpost
   env_file:
       - env/flip.env

#Live catalogue

livecat:
    restart: always
    image: eeacms/flis.live-catalogue
    links:
        - dbsql
    env_file:
        - env/livecat.env

#Metadata

metadata:
    restart: always
    image: eeacms/flis.metadata
    links:
        - dbsql
    env_file:
        - env/metadata.env

#Frontend server

frontend:
    restart: always
    build: frontend
    links:
        - hstool
        - flip
        - livecat
        - metadata
    volumes_from:
        - hstool
        - flip
        - livecat
        - metadata
    ports:
        - 80:80
    env_file:
        - env/nginx.env
